
#pragma once

G_BEGIN_DECLS

typedef enum
{
  POLYHYMNIA_PLAYER_PLAYBACK_STATUS_UNKNOWN = 0,
  POLYHYMNIA_PLAYER_PLAYBACK_STATUS_STOPPED,
  POLYHYMNIA_PLAYER_PLAYBACK_STATUS_PLAYING,
  POLYHYMNIA_PLAYER_PLAYBACK_STATUS_PAUSED,
} PolyhymniaPlayerPlaybackStatus;

G_END_DECLS
